### PR TITLE
Upgrade kubernetes 1.30+Upgrade packages+Upgrade go 1.23.3

### PR DESCRIPTION
**Pull request by zkonak**
Upgrade kubernetes packages to 1.30.6 + Upgrade packages + Upgrade go 1.23.3

### CODE REVIEW

**Review by evrardjp — DISMISSED** [review]
Can you add some tests? At list staticcheck (It would explain the ioutils -> os) or better - e2e tests.

**Comment by evrardjp-cagip** [comment]
Did you update the toolchain before doing the update of go?

**Review by evrardjp-cagip — CHANGES_REQUESTED** [review]
jwt-go and ozzo-validation should also be bumped. Let's discuss this in a call.

**Review by evrardjp-cagip — APPROVED** [review]
Let's do only this at the moment, then do jwt-go and ozzo-validation in another PR.

**Pull request merged**
